kind: live
name: Run Jupyter notebook
author: Alexey Naiden
descr: runs Jupter notebook with your image
inputs:
  arg1:
    descr: param 1
  arg2:
    descr: param 2
    default: value 2
job:
    multi: True
    image: $[[ images.myimage.ref ]]
    http_port: 8888
    http_auth: True
    browse: True
    detach: True
    volumes:
      - $[[ volumes.data.ref_ro ]]
      - $[[ volumes.code.ref_rw ]]
      - $[[ volumes.config.ref_ro ]]
      - $[[ volumes.notebooks.ref_rw ]]
      - $[[ volumes.results.ref_rw ]]
    env:
      PYTHONPATH: $[[ volumes.code.mount ]]
    cmd: >-
      jupyter $[[ multi.args ]]
        --no-browser
        --ip=0.0.0.0
        --allow-root
        --NotebookApp.token=
        --notebook-dir=$[[ volumes.notebooks.mount ]]